
baseurl: "/vintage-drums"

exclude: ['grunt/']

collections:
  sixties:
    output: false
  seventies:
    output: false
  eighties:
    output: false
  nineties:
    output: false



# Serving
port: 1234